spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR