spring:
  application:
    name: fraud-detection-service

  datasource:
    url: jdbc:mysql://localhost:3306/fraud_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "[spring.json.value.default.type]": "com.banking.frauddetectionservice.kafka.TransactionEvent"
        "[spring.json.trusted.packages]": "com.banking.transactionservice.kafka,com.banking.frauddetectionservice.kafka"
        "[spring.json.use.type.headers]": "false"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

fraud:
  amount:
    average-multiplier: 3.0

server:
  port: 8084

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR